[analytics]
tracking_id = "G-XXXXXXXXXX"  # Replace with your Google Analytics tracking ID
app_url = "https://your-app-url.com"  # Replace with your app's URL
app_name = "Sports Card Analyzer"  # Replace with your app's name 