# Firebase Configuration
[firebase]
type = "service_account"
project_id = "sports-card-analyzer"
private_key_id = "a84bf8493f545cf1359f6833efac3cf56ca49679"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZ7xyfQNtFzrpR\nbu1HyYaw+BdNRlFvWC9mYMwji3w4lIRzDHC46jThZrT9mK7Qr2EXDjt9QOgSjQnQ\nTjZv6+gzoRN6mvoj/0R07JCv9I73CNzkYTVcWzY0wMTEhBdA+kMjstmALvJi9cLb\nnrjhMpFnJFVojEyIA6hz4UNXqmHNvN/tQTIltMtNThwc0OM+v88MFfsRqIjctbVw\n07QCT+EIe0SLshC+WO9XjjrsWTj7dNFzI88G/x5h2giSCC34uobfP0xuwee1bggN\noSs8cZMFBrraJyX+267uRuT1R0OXfourXnAFwKUDUkZ41VXdyX/9Pk/wqZcXuptR\nSaV8zOZ1AgMBAAECggEAE9EH8Wp4hUvqiXQ1y1w4C403TA/liOd52/ynGwZTEgzw\ni3JftTZquKpaWhvvRAHn26ojN2nagRTeCA524ev6jbb1RSnb/N6uUee9wqEW9y9m\nvGcqkZP+bkZzWPcbmpZSfASDYoXorJuwdPRsdDU91GDa4TrP2WIF1rvPnw1Z9OcM\nukoH33PniudmNqv+aQ2WcjA1Z4bnd7gUeqxz4nYwmdOYumvHlM79M/HvPOvkXQKY\nlyiuVcUlbk6pvjrxdVqL5ayO5AtIiXG7/TCpiKpufXUHtFBDsWIWWqkuWN/uhmzL\nALaFGcQGzOTD4yLqQPgw58dvsug+sPUe0JELgS69ewKBgQDPrIqypvj9kJyrA8s4\nVl3kWKA5hGIoc819IOMNkISPP3jOMaYbCfxDO8UVAMSNUlulhC76AOUdeQch6omv\nDlRd10HxE4ILyn3CYqdnyCq11aEZXEDD2KAR2omrh2gf/DZzWGhkxo8nyGcNh+2v\njNbSRZSgxCgIJgg5HBSn2HEgkwKBgQC9wTK3yYF/3LeOs0uoGDLCLz7ENG0HY6/H\n4NC/ZjdPDca+z4UazSkLCLNm1rSt0WABLqx9PNDdjQ7rDqkCybq+iQfAojjJYZt+\n1OKRyadBHlvUhL5GThcWomGVL2WShSgpOuX3vNcj9ossPYhI1mn3YFXEFHiRmmZ3\nidfkDQEp1wKBgDXUGENESkeXIzSkkBkzMbUNT8J40OSBV6L2UkPi0Kk8n3h6n/5k\nMTHQHT5ba5bh4QVe5LpCXyCrjTC6VSO9yBpmwB3Xm56oxr4Kyi95T7DABbjIE7Vv\nwdW+2m5Oc6vOuOJe6PguC08Zf7SfJfmZvNjV1jdxgJrUGM+MusHitTfnAoGAcBYH\nF3j3/ccqxigysIBau0mdEdjF7m98Dd1GcUi3swK4O03pmgNGEzZ4gm6hG2tqAkjH\nqtKZrcT84uwt+W+f15yp76fjU1FMwIaPrv4mxdhg9g/TNUQ7bytL6QuuO/Zb2r7n\nyIbLrnqbiu5t6lh9D5rgDorpDVje3g2WcScdYNECgYBO/w9fiIryFQJvJ7JyFdEf\nFiQSPbs8MWwBu5azxEmJLN8f2Oy+NamDR2UzE3ehI1B8KT9fHXXIz4PH6+2djehC\nUulufIna+npyFXq2hlaX7P0CrxP42Dc5Sg2eTBKCIRhXIFEo2nold7ZPwLDyoO+b\nMiPt6Kh6S5cwtf2U52+jLw==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@sports-card-analyzer.iam.gserviceaccount.com"
client_id = "115668087168581468293"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-card-analyzer.iam.gserviceaccount.com"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-client-email%40your-project-id.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
api_key = "AIzaSyDqXGxXqXqXqXqXqXqXqXqXqXqXqXqXqXq"
auth_domain = "sportscardanalyzer.firebaseapp.com"
storage_bucket = "sportscardanalyzer.appspot.com"
messaging_sender_id = "123456789012"
app_id = "1:123456789012:web:abcdef1234567890"
measurement_id = "G-YNZTKCHQT0"

# Stripe Configuration
[stripe]
secret_key = "sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
webhook_secret = "whsec_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
basic_plan_price_id = "price_basic_test_XXXXXXXXXXXXXXXX"
premium_plan_price_id = "price_premium_test_XXXXXXXXXXXXXXXX"
success_url = "https://sportscardanalyzer.streamlit.app/subscription?success=true"
cancel_url = "https://sportscardanalyzer.streamlit.app/subscription?canceled=true"

# Google Analytics Configuration
[google_analytics]
tracking_id = "G-YNZTKCHQT0"  # Sports Card Analyzer Pro measurement ID

# App Configuration
[app]
url = "https://sportscardanalyzer.streamlit.app"  # Your Streamlit app URL
name = "Sports Card Analyzer Pro"
stream_id = "10453424513"